[package]
name = "sienna"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
imgref = "1.11.0"
kolor = "0.1.9"
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "pi_camera_benchmark"
harness = false
